# Generated by Django 3.0.8 on 2020-07-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_article',
            name='author',
        ),
    ]
